In [1]:
import numpy as np
import time

In [2]:
#for checking time difference betn python-list and ndArrays

size = 10_000_000
py_list = list(range(size))
st_time = time.time()
sq_list = [i**2 for i in py_list]
ed_time = time.time()
print(f"{(ed_time-st_time)}")

1.5237634181976318


In [3]:
#for checking memory storage usage 
import sys

np_array = np.array(py_list)
print(f"size of python list is {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"size of python list is {np_array.nbytes} bytes")

size of python list is 800000560000000 bytes
size of python list is 80000000 bytes


In [4]:
#creating array from scratch
arr = np.linspace(1,50,4 , dtype = "int64")
print(arr,arr.shape)

arr1 = np.arange(1,100,2)
print(arr1)

arr2 = np.full((5,4),50)
print(arr2,arr2.shape)

[ 1 17 33 50] (4,)
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]] (5, 4)


In [5]:
#properties of numpy
arr = np.array([1,2,3,4,5])
print(arr.astype(np.float64),arr.size,arr.shape,arr.ndim)

arr2 = np.full((5,6),11, dtype = "float64")
print(arr2,type(arr2))

[1. 2. 3. 4. 5.] 5 (5,) 1
[[11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11.]] <class 'numpy.ndarray'>


In [6]:
#operations on numpy
arr = np.array([[2,3],[5,6],[9,6]])

print(arr,arr.shape)

reshape = arr.reshape((2,3))
print(reshape)
flatten = arr.flatten()
print(flatten)
print(arr[0][1])
print(flatten[[1,5,3]])
print(flatten[:4])

[[2 3]
 [5 6]
 [9 6]] (3, 2)
[[2 3 5]
 [6 9 6]]
[2 3 5 6 9 6]
3
[3 6 6]
[2 3 5 6]


In [12]:
#multidimensional array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

sum_of_array = np.sum(arr , axis = 1)
print(sum_of_array,arr)
print(arr[0:2 , 1:])

[ 6 15 24] [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [21]:
#3D-array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,0],[9,1]]])

print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,2,0])
#slicing
print(arr3D[:1,0:2,:1])

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [9 1]]] (2, 3, 2)
9
[[[1]
  [3]]]
